/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.vistas;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import ufps.logicaNegocio.Binario;
import ufps.logicaNegocio.SistemaBinario;

/**
 *
 * 
 */
public class FormBinario extends javax.swing.JFrame {

    
    private SistemaBinario mySistemaBinario;
    
    String editar = "Editar";
    String cargar = "Cargar Datos";
    
    /**
     * Creates new form FormBinario
     */
    public FormBinario() {
        initComponents();
        this.mySistemaBinario = new SistemaBinario();
        this.disabledAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanelBody = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        comboOperacionBinario1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboOperacionBinario2 = new javax.swing.JComboBox<>();
        comboOperacion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textOperacionResultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textDatos = new javax.swing.JTextField();
        toggleCargarDatos = new javax.swing.JToggleButton();
        botonBorrarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        comboConversionBinario1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        comboConversionOperacion = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textConversionResultado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        comboOperacionAdicional = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textOperacionAdicionalResultado = new javax.swing.JTextField();

        jLabel5.setText("Binario 2");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "101", "1111", "0101" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Binario 2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "101", "1111", "0101" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Binario 1:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Binario 2");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "101", "1111", "0101" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Operación");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Resultado:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setText("100");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 231, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBody.setBackground(new java.awt.Color(247, 247, 247));

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        comboOperacionBinario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboOperacionBinario1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "101", "1111", "0101" }));
        comboOperacionBinario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOperacionBinario1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Binario 1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Binario 2");

        comboOperacionBinario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboOperacionBinario2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "101", "1111", "0101" }));
        comboOperacionBinario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOperacionBinario2ActionPerformed(evt);
            }
        });

        comboOperacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*" }));
        comboOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOperacionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Operación");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Resultado:");

        textOperacionResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textOperacionResultado.setText("100");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboOperacionBinario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboOperacionBinario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(textOperacionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOperacionBinario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOperacionBinario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textOperacionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Carga de Datos"));

        jLabel2.setText("Digite los binarios separados por \",\":");

        textDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textDatos.setText("11, 101, 1111, 0101");
        textDatos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDatosFocusLost(evt);
            }
        });
        textDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDatosActionPerformed(evt);
            }
        });
        textDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textDatosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textDatosKeyReleased(evt);
            }
        });

        toggleCargarDatos.setText("Cargar Datos");
        toggleCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleCargarDatosActionPerformed(evt);
            }
        });

        botonBorrarDatos.setText("Borrar Datos");
        botonBorrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(toggleCargarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBorrarDatos)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleCargarDatos)
                    .addComponent(botonBorrarDatos)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Binario");

        jPanel4.setBackground(new java.awt.Color(247, 247, 247));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Conversiones"));

        comboConversionBinario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboConversionBinario1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "101", "1111", "0101" }));
        comboConversionBinario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConversionBinario1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Binario 1:");

        comboConversionOperacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboConversionOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Hexadecimal" }));
        comboConversionOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConversionOperacionActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Convertir a:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Resultado:");

        textConversionResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textConversionResultado.setText("3");

        jPanel5.setBackground(new java.awt.Color(247, 247, 247));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones Adicionales"));

        comboOperacionAdicional.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboOperacionAdicional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obtener el Menor", "Obtener el Mayor", "Obtener el Binario que más se repite", "Obtener Suma Total" }));
        comboOperacionAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOperacionAdicionalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Operación:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Resultado:");

        textOperacionAdicionalResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textOperacionAdicionalResultado.setText("11");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(comboOperacionAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(textOperacionAdicionalResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(comboOperacionAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textOperacionAdicionalResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboConversionBinario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboConversionOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(textConversionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboConversionBinario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboConversionOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textConversionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBodyLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(8, Short.MAX_VALUE)))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBodyLayout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleCargarDatosActionPerformed
       cargarDatos();
    }//GEN-LAST:event_toggleCargarDatosActionPerformed

    private void comboOperacionBinario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOperacionBinario1ActionPerformed
        this.getResultadoOperacion();
    }//GEN-LAST:event_comboOperacionBinario1ActionPerformed

    private void textDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDatosActionPerformed

    private void comboOperacionBinario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOperacionBinario2ActionPerformed
        this.getResultadoOperacion();
    }//GEN-LAST:event_comboOperacionBinario2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void comboOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOperacionActionPerformed
        this.getResultadoOperacion();
    }//GEN-LAST:event_comboOperacionActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void comboConversionBinario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConversionBinario1ActionPerformed
       getResultadoOperacionConversion();
    }//GEN-LAST:event_comboConversionBinario1ActionPerformed

    private void comboConversionOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConversionOperacionActionPerformed
       getResultadoOperacionConversion();
    }//GEN-LAST:event_comboConversionOperacionActionPerformed

    private void comboOperacionAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOperacionAdicionalActionPerformed
       this.getResultadoOperacionAdicional();
    }//GEN-LAST:event_comboOperacionAdicionalActionPerformed

    private void botonBorrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarDatosActionPerformed
       this.removerDatos();
    }//GEN-LAST:event_botonBorrarDatosActionPerformed

    private void textDatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDatosKeyPressed
       
    }//GEN-LAST:event_textDatosKeyPressed

    private void textDatosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDatosFocusLost
      // this.isEnabledRemoverDatos();
    }//GEN-LAST:event_textDatosFocusLost

    private void textDatosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDatosKeyReleased
       this.isEnabledRemoverDatos();
    }//GEN-LAST:event_textDatosKeyReleased

    private void cargarDatos(){
        if(true == this.toggleCargarDatos.isSelected()){
           boolean datosCargados = cargarDatos(textDatos.getText());
           if( datosCargados ){
                this.enabledAll();
                setEnabledCargarDatos(false);
                this.getResultadoOperacionAdicional();
                this.getResultadoOperacionConversion();
           }else{
               this.setEnabledCargarDatos(true);
           }
       }else{
           this.setEnabledCargarDatos(true);
           this.mySistemaBinario = new SistemaBinario();
           this.disabledAll();
       }
    }
    
    private boolean cargarDatos(String datos){
        this.setMySistemaBinario(datos);
        if(this.mySistemaBinario != null && this.mySistemaBinario.getBinarios() != null){
           mostrarBinarios();
           return true;
        }else{
           this.showMessageBinariosInvalidos();
           return false;
        }
        
    }
    
    private void showMessageBinariosInvalidos(){
        String input = textDatos.getText();
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe digitar almenos un numero binario");
        }else{
            String[] cadena = input.split(",");
            if(cadena.length <= 0){
                 JOptionPane.showMessageDialog(this, "Recuerde separa los binarios con comas \n Eje:  001 , 101 ");
            }else{
                boolean numeroNoValido = false;
                for(String numero : cadena){
                    if( false ==  numero.replaceAll("0", "").replaceAll("1", "").isEmpty()){
                        numeroNoValido = true;
                    }
                }
                if(numeroNoValido){
                   JOptionPane.showMessageDialog(this, "Solo ingreso binarios con 1 y 0 \n Eje:  001 , 101 ");
                }
            }
        }
    }
    
    private void setMySistemaBinario(String datos){
        if(false == datos.isEmpty() ){
            String[] binarios = datos.split(",");
            if(binarios.length > 0){
                this.mySistemaBinario = new SistemaBinario();
                for (String registro : binarios) {
                    if(false == registro.isEmpty()){
                        
                        this.mySistemaBinario.add(new Binario(registro));
                    }
                }
            }
        }    
    }
    
    private void mostrarBinarios(){
            mostraBinariosOperacion();
            mostraBinariosConversiones();
    }
    
    private void mostraBinariosOperacion(){
        comboOperacionBinario1.removeAllItems();
        comboOperacionBinario2.removeAllItems();
        for(Binario binario : this.mySistemaBinario.getBinarios()){
            comboOperacionBinario1.addItem(binario.toString());
            comboOperacionBinario2.addItem(binario.toString());
        } 
    }
    
    private void mostraBinariosConversiones(){
        comboConversionBinario1.removeAllItems();
        for(Binario binario : this.mySistemaBinario.getBinarios()){
            comboConversionBinario1.addItem(binario.toString());
        }
    }
    
    private void isEnabledRemoverDatos(){
        String datos = textDatos.getText();
        if(false == datos.isEmpty()){
            botonBorrarDatos.setEnabled(true);
            this.setEnabledCargarDatos(true);
        }else{
            botonBorrarDatos.setEnabled(false);
            this.toggleCargarDatos.setEnabled(false);
        }
    }
    
    private void removerDatos(){
        textDatos.setText("");
        this.mySistemaBinario = new SistemaBinario();
        botonBorrarDatos.setEnabled(false);
        this.setEnabledCargarDatos(true);
        this.toggleCargarDatos.setEnabled(false);
        this.disabledAll();
    }
    
    
    private void getResultadoOperacion(){
        int binario1 = comboOperacionBinario1.getSelectedIndex();
        String operacion = this.comboOperacion.getSelectedItem().toString();
        int binario2 = comboOperacionBinario2.getSelectedIndex();
        if(binario1 != -1 && binario2 != -1){
            String resultado = this.getOperacion(operacion, binario1, binario2);
            textOperacionResultado.setText(resultado); 
        }
        
    }
    
    private String getOperacion(String operacion, int binario1, int binario2){
        String resultado = "";
        if(operacion.equalsIgnoreCase("+")){
            resultado = this.mySistemaBinario.getSuma(binario1, binario2).toString();
        }
        if(operacion.equalsIgnoreCase("-") ){
            resultado = this.mySistemaBinario.getResta(binario1, binario2).toString();
            resultado += "   ( " + this.mySistemaBinario.formatBinResta(resultado) + " ) ";
        }
        if(operacion.equalsIgnoreCase("*")){
            resultado = this.mySistemaBinario.getMultiplica(binario1, binario2).toString();
        }
        return resultado;
    }
    
    private void getResultadoOperacionConversion(){
        int binario1 = comboConversionBinario1.getSelectedIndex();
        String operacion = this.comboConversionOperacion.getSelectedItem().toString();
        if(binario1 != -1){
            String resultado = this.getOperacionConversion(operacion, binario1);
            textConversionResultado.setText(resultado); 
        }
        
    }
    
    private String getOperacionConversion(String operacion, int binario){
        String resultado = "";
        if(operacion.equalsIgnoreCase("Decimal")){
            resultado = ""+this.mySistemaBinario.getDecimal(binario);
        }
        if(operacion.equalsIgnoreCase("Hexadecimal") ){
            resultado = this.mySistemaBinario.getHexaDecimal(binario);
        }
        return resultado;
    }
    
    private void getResultadoOperacionAdicional(){
        String operacion = comboOperacionAdicional.getSelectedItem().toString();
        String resultado = getOperacionAdicional(operacion);
        textOperacionAdicionalResultado.setText(resultado);
    }
    
    private String getOperacionAdicional(String operacion){
        String resultado = "";
        if(operacion.equalsIgnoreCase("Obtener el Menor")){
            resultado = this.mySistemaBinario.getMenor().toString();
        }
        if(operacion.equalsIgnoreCase("Obtener el Mayor") ){
            resultado = this.mySistemaBinario.getMayor().toString();
        }
        if(operacion.equalsIgnoreCase("Obtener el Binario que más se repite")){
            Binario[] masRepetido = this.mySistemaBinario.getMas_SeRepite();
            resultado = masRepetido[0].toString();
        }
        if(operacion.equalsIgnoreCase("Obtener Suma Total")){
            resultado = this.mySistemaBinario.getSumaTotal().toString();
        }
        return resultado;
    }
    
    private void disabledAll(){
        boolean enabled = false; 
        setEnabledAll(enabled);
    }
    
    private void enabledAll(){
        boolean enabled = true; 
        setEnabledAll(enabled);        
    }
    
    private void setEnabledAll(boolean enabled){
        this.comboConversionBinario1.setEnabled(enabled);
        this.comboConversionOperacion.setEnabled(enabled);
        this.comboOperacion.setEnabled(enabled);
        this.comboOperacionAdicional.setEnabled(enabled);
        this.comboOperacionBinario1.setEnabled(enabled);
        this.comboOperacionBinario2.setEnabled(enabled);
        this.textConversionResultado.setEnabled(enabled);
        this.textOperacionAdicionalResultado.setEnabled(enabled);
        this.textOperacionResultado.setEnabled(enabled);
    }
    
    private void setEnabledCargarDatos(boolean enabled){
        if(enabled){
            textDatos.setEnabled(true);
            this.toggleCargarDatos.setEnabled(true);
            this.toggleCargarDatos.setText(cargar);
            this.toggleCargarDatos.setSelected(false);
            this.textDatos.requestFocus();
        }else{
            textDatos.setEnabled(false);
            this.toggleCargarDatos.setText(editar);
            this.toggleCargarDatos.setSelected(true);
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarDatos;
    private javax.swing.JComboBox<String> comboConversionBinario1;
    private javax.swing.JComboBox<String> comboConversionOperacion;
    private javax.swing.JComboBox<String> comboOperacion;
    private javax.swing.JComboBox<String> comboOperacionAdicional;
    private javax.swing.JComboBox<String> comboOperacionBinario1;
    private javax.swing.JComboBox<String> comboOperacionBinario2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField textConversionResultado;
    private javax.swing.JTextField textDatos;
    private javax.swing.JTextField textOperacionAdicionalResultado;
    private javax.swing.JTextField textOperacionResultado;
    private javax.swing.JToggleButton toggleCargarDatos;
    // End of variables declaration//GEN-END:variables
}
